In [2]:
import os
import numpy as np
import pandas as pd

# Define the directory and file path
directory = r'C:\haris\Downloads\Machine Learning\Supervised Learning'
file_path = os.path.join(directory, 'age_salary.csv')

# Create the directory if it doesn't exist
os.makedirs(directory, exist_ok=True)

# Set a seed for reproducibility
np.random.seed(42)

# Generate 100 ages between 25 and 65
ages = np.random.randint(25, 66, size=100)

# Create a correlated salary with some random noise
salaries = ages * 1000 + np.random.normal(0, 5000, size=100)

# Create a DataFrame
data = pd.DataFrame({
    'Age': ages,
    'Salary': salaries
})

# Save the DataFrame to a CSV file
data.to_csv(file_path, index=False)

file_path


'C:\\haris\\Downloads\\Machine Learning\\Supervised Learning\\age_salary.csv'

In [3]:
df=pd.read_csv("C:\\haris\\Downloads\\Machine Learning\\Supervised Learning\\age_salary.csv")

In [4]:
df.sample(5)

Age        Salary
4    45  49062.629112
11   60  67690.182832
46   32  41430.929506
55   28  29507.736712
57   42  36156.609812

In [5]:
df.corr()

Age    Salary
Age     1.000000  0.925439
Salary  0.925439  1.000000

In [6]:
df.describe()

Age        Salary
count  100.00000    100.000000
mean    43.94000  43863.149977
std     11.78153  12578.221895
min     25.00000  13901.274480
25%     33.00000  33453.406075
50%     44.50000  42664.215412
75%     52.25000  52145.769376
max     65.00000  72749.672025

In [7]:
df.describe

<bound method NDFrame.describe of     Age        Salary
0    63  60604.128811
1    53  52071.705117
2    39  33468.325130
3    32  26018.966880
4    45  49062.629112
..  ...           ...
95   52  48428.242910
96   31  40328.872556
97   33  35369.164605
98   32  26043.482514
99   36  39282.768043

[100 rows x 2 columns]>

In [7]:
df.shape

(100, 2)

OUTLIERS

In [9]:
from scipy.stats import zscore
df=df[(np.abs(zscore(df))<3).all(axis=1)]
df

Age        Salary
0    63  60604.128811
1    53  52071.705117
2    39  33468.325130
3    32  26018.966880
4    45  49062.629112
..  ...           ...
95   52  48428.242910
96   31  40328.872556
97   33  35369.164605
98   32  26043.482514
99   36  39282.768043

[100 rows x 2 columns]

In [8]:
x=df['Age']
y=df['Salary']

In [9]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test=train_test_split(x,y)

In [11]:
X_train=np.reshape(X_train,(-1,1))
x_test=np.reshape(x_test,(-1,1))

In [15]:
X_train

array([[59],
       [50],
       [62],
       [53],
       [64],
       [59],
       [44],
       [52],
       [48],
       [41],
       [26],
       [25],
       [31],
       [65],
       [32],
       [39],
       [40],
       [63],
       [49],
       [49],
       [48],
       [39],
       [52],
       [49],
       [33],
       [59],
       [61],
       [45],
       [53],
       [28],
       [63],
       [34],
       [60],
       [35],
       [57],
       [33],
       [55],
       [42],
       [49],
       [65],
       [57],
       [35],
       [52],
       [26],
       [54],
       [39],
       [64],
       [46],
       [32],
       [38],
       [30],
       [32],
       [63],
       [47],
       [45],
       [25],
       [28],
       [47],
       [58],
       [26],
       [27],
       [45],
       [50],
       [64],
       [38],
       [36],
       [29],
       [31],
       [45],
       [60],
       [38],
       [42],
       [46],
       [60],
       [48]], dtype=int64)

In [16]:
from sklearn.linear_model import LinearRegression
lin=LinearRegression()
model=lin.fit(X_train,Y_train)
model

LinearRegression()

In [15]:
print(lin.coef_)
print(lin.intercept_)

[955.80472935]
2543.423804803104


In [16]:
print(x_test[:5])
print(y_test[:5])

[[50]
 [27]
 [48]
 [39]
 [33]]
58    55714.114073
30    27485.387747
10    49806.978028
77    37389.692419
34    31039.459234
Name: Salary, dtype: float64


In [77]:
sales_pred=lin.predict(x_test[:5])
sales_pred

array([58406.95965639, 56439.18280916, 35777.52591324, 49551.96384386,
       51519.74069109])

In [17]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mserror=mean_squared_error(y_test[:5],sales_pred)
maerror=mean_absolute_error(y_test[:5],sales_pred)
print(mserror)
print(maerror)


NameError: name 'sales_pred' is not defined